title: Modern Computer Architecture and Organization
description: "<bold>Modern Computer Architecture and Organization,</bold> by Jim Ledin. Published by Packt Publishing."
show_downloads: true

remote_theme: https://github.com/pisaucer/tweakprimer
plugins:
- jekyll-remote-theme
